--
-- PostgreSQL database dump
--

\restrict efqQTXbfv5FjeJitMNp5s3bpEGSihCnnMeGR4JYWdx4ONlN2VszNIxdsFrCM1y0

-- Dumped from database version 18.3 (Homebrew)
-- Dumped by pg_dump version 18.2

-- Started on 2026-04-02 10:32:31 CEST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16389)
-- Name: Capteur; Type: TABLE; Schema: public; Owner: eleaweber
--

CREATE TABLE public."Capteur" (
    nom character varying(100),
    "Localisation" numeric(50,0)[],
    "Responsable" character varying(100),
    "Id" integer NOT NULL,
    "Id_instrument" integer
);


ALTER TABLE public."Capteur" OWNER TO eleaweber;

--
-- TOC entry 220 (class 1259 OID 16394)
-- Name: Capteur_Id_seq; Type: SEQUENCE; Schema: public; Owner: eleaweber
--

CREATE SEQUENCE public."Capteur_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."Capteur_Id_seq" OWNER TO eleaweber;

--
-- TOC entry 3862 (class 0 OID 0)
-- Dependencies: 220
-- Name: Capteur_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: eleaweber
--

ALTER SEQUENCE public."Capteur_Id_seq" OWNED BY public."Capteur"."Id";


--
-- TOC entry 222 (class 1259 OID 17424)
-- Name: instrument; Type: TABLE; Schema: public; Owner: eleaweber
--

CREATE TABLE public.instrument (
    id_instrument integer NOT NULL,
    num_instrument integer,
    modele character varying(255)
);


ALTER TABLE public.instrument OWNER TO eleaweber;

--
-- TOC entry 221 (class 1259 OID 17423)
-- Name: instrument_id_instrument_seq; Type: SEQUENCE; Schema: public; Owner: eleaweber
--

ALTER TABLE public.instrument ALTER COLUMN id_instrument ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.instrument_id_instrument_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3700 (class 2604 OID 16395)
-- Name: Capteur Id; Type: DEFAULT; Schema: public; Owner: eleaweber
--

ALTER TABLE ONLY public."Capteur" ALTER COLUMN "Id" SET DEFAULT nextval('public."Capteur_Id_seq"'::regclass);


--
-- TOC entry 3853 (class 0 OID 16389)
-- Dependencies: 219
-- Data for Name: Capteur; Type: TABLE DATA; Schema: public; Owner: eleaweber
--

COPY public."Capteur" (nom, "Localisation", "Responsable", "Id", "Id_instrument") FROM stdin;
Lux	{22,5}	Milou	567	1000
HydroLab	{122,46}	Milou	876	1000
T400	{41,2}	Dupont	334	2345
Thermo2	{2,67}	Dupont	987	2345
\.


--
-- TOC entry 3856 (class 0 OID 17424)
-- Dependencies: 222
-- Data for Name: instrument; Type: TABLE DATA; Schema: public; Owner: eleaweber
--

COPY public.instrument (id_instrument, num_instrument, modele) FROM stdin;
1000	1	station meteo
2345	2	thermologger
\.


--
-- TOC entry 3863 (class 0 OID 0)
-- Dependencies: 220
-- Name: Capteur_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: eleaweber
--

SELECT pg_catalog.setval('public."Capteur_Id_seq"', 1, false);


--
-- TOC entry 3864 (class 0 OID 0)
-- Dependencies: 221
-- Name: instrument_id_instrument_seq; Type: SEQUENCE SET; Schema: public; Owner: eleaweber
--

SELECT pg_catalog.setval('public.instrument_id_instrument_seq', 1, false);


--
-- TOC entry 3702 (class 2606 OID 16403)
-- Name: Capteur PK_id; Type: CONSTRAINT; Schema: public; Owner: eleaweber
--

ALTER TABLE ONLY public."Capteur"
    ADD CONSTRAINT "PK_id" PRIMARY KEY ("Id");


--
-- TOC entry 3704 (class 2606 OID 17429)
-- Name: instrument pk_instrument_mesure; Type: CONSTRAINT; Schema: public; Owner: eleaweber
--

ALTER TABLE ONLY public.instrument
    ADD CONSTRAINT pk_instrument_mesure PRIMARY KEY (id_instrument);


--
-- TOC entry 3705 (class 2606 OID 17430)
-- Name: Capteur fk_capteur_instrument; Type: FK CONSTRAINT; Schema: public; Owner: eleaweber
--

ALTER TABLE ONLY public."Capteur"
    ADD CONSTRAINT fk_capteur_instrument FOREIGN KEY ("Id_instrument") REFERENCES public.instrument(id_instrument);


-- Completed on 2026-04-02 10:32:31 CEST

--
-- PostgreSQL database dump complete
--

\unrestrict efqQTXbfv5FjeJitMNp5s3bpEGSihCnnMeGR4JYWdx4ONlN2VszNIxdsFrCM1y0

