-- =========================================================
-- SUPPRESSION
-- =========================================================

DROP TABLE IF EXISTS correction_mesure CASCADE;
DROP TABLE IF EXISTS coefficient_correcteur CASCADE;
DROP TABLE IF EXISTS mesure CASCADE;
DROP TABLE IF EXISTS source_donnees CASCADE;
DROP TABLE IF EXISTS serie_temporelle CASCADE;
DROP TABLE IF EXISTS capteur_localise CASCADE;
DROP TABLE IF EXISTS remplacement_capteur CASCADE;
DROP TABLE IF EXISTS maintenance_capteur CASCADE;
DROP TABLE IF EXISTS capteur CASCADE;
DROP TABLE IF EXISTS instrument_projet CASCADE;
DROP TABLE IF EXISTS est_referent_de CASCADE;
DROP TABLE IF EXISTS remplacement_instrument CASCADE;
DROP TABLE IF EXISTS collecte_instrument CASCADE;
DROP TABLE IF EXISTS instrument_mesure CASCADE;
DROP TABLE IF EXISTS structure_fichier CASCADE;
DROP TABLE IF EXISTS possede_categorie CASCADE;
DROP TABLE IF EXISTS variable_mesuree CASCADE;
DROP TABLE IF EXISTS categorie_variable CASCADE;
DROP TABLE IF EXISTS biodiversite_localisee CASCADE;
DROP TABLE IF EXISTS localisation CASCADE;
DROP TABLE IF EXISTS milieu_specifique CASCADE;
DROP TABLE IF EXISTS biodiversite CASCADE;
DROP TABLE IF EXISTS membre_projet CASCADE;
DROP TABLE IF EXISTS projet CASCADE;
DROP TABLE IF EXISTS membre_groupe CASCADE;
DROP TABLE IF EXISTS groupe_recolte CASCADE;
DROP TABLE IF EXISTS responsable_fichier CASCADE;
DROP TABLE IF EXISTS referent_instrument CASCADE;
DROP TABLE IF EXISTS recolteur CASCADE;
DROP TABLE IF EXISTS collecteur CASCADE;
DROP TABLE IF EXISTS capteur_generique CASCADE;
DROP TABLE IF EXISTS personne CASCADE;

-- =========================================================
-- TABLES DE BASE
-- =========================================================

CREATE TABLE personne (
    id_personne INT GENERATED BY DEFAULT AS IDENTITY,
    nom VARCHAR(255),
    prenom VARCHAR(255),
    adresse_mail VARCHAR(255) NOT NULL,
    fonction VARCHAR(255),
    id_hierarchie INT,
    CONSTRAINT PK_personne PRIMARY KEY (id_personne),
    CONSTRAINT FK_personne_hierarchie
        FOREIGN KEY (id_hierarchie)
        REFERENCES personne (id_personne)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT CK_personne_differente
        CHECK (id_personne <> id_hierarchie),
    CONSTRAINT uq_personne_mail
        UNIQUE (adresse_mail)
);

CREATE TABLE capteur_generique (
    id_capteur_generique INT GENERATED BY DEFAULT AS IDENTITY,
    description TEXT NOT NULL,
    CONSTRAINT PK_capteur_generique PRIMARY KEY (id_capteur_generique),
    CONSTRAINT uq_capteur_generique_description UNIQUE (description)
);

CREATE TABLE collecteur (
    id_collecteur INT,
    CONSTRAINT PK_collecteur PRIMARY KEY (id_collecteur),
    CONSTRAINT FK_collecteur_personne
        FOREIGN KEY (id_collecteur)
        REFERENCES personne (id_personne)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE recolteur (
    id_recolteur INT,
    id_capteur_generique INT,
    CONSTRAINT PK_recolteur PRIMARY KEY (id_recolteur, id_capteur_generique),
    CONSTRAINT FK_recolteur_personne
        FOREIGN KEY (id_recolteur)
        REFERENCES personne (id_personne)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_recolteur_capteur_generique
        FOREIGN KEY (id_capteur_generique)
        REFERENCES capteur_generique (id_capteur_generique)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE referent_instrument (
    id_referent INT,
    CONSTRAINT PK_referent_instrument PRIMARY KEY (id_referent),
    CONSTRAINT FK_referent_instrument_personne
        FOREIGN KEY (id_referent)
        REFERENCES personne (id_personne)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE responsable_fichier (
    id_responsable INT,
    CONSTRAINT PK_responsable_fichier PRIMARY KEY (id_responsable),
    CONSTRAINT FK_responsable_fichier_personne
        FOREIGN KEY (id_responsable)
        REFERENCES personne (id_personne)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE groupe_recolte (
    id_groupe INT GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT PK_groupe_recolte PRIMARY KEY (id_groupe)
);

CREATE TABLE projet (
    id_projet INT GENERATED BY DEFAULT AS IDENTITY,
    nom_responsable VARCHAR(255),
    mail_responsable VARCHAR(255),
    date_debut DATE,
    date_fin DATE,
    CONSTRAINT PK_projet PRIMARY KEY (id_projet),
    CONSTRAINT CK_projet_dates CHECK (date_debut <= date_fin) 
);

CREATE TABLE biodiversite (
    id_biodiversite INT GENERATED BY DEFAULT AS IDENTITY,
    description_bio TEXT,
    famille VARCHAR(255),
    CONSTRAINT PK_biodiversite PRIMARY KEY (id_biodiversite)
);

CREATE TABLE milieu_specifique (
    id_milieu INT GENERATED BY DEFAULT AS IDENTITY,
    categorie VARCHAR(255),
    description_milieu TEXT,
    CONSTRAINT PK_milieu_specifique PRIMARY KEY (id_milieu)
);

CREATE TABLE localisation (
    id_localisation INT GENERATED BY DEFAULT AS IDENTITY,
    altitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    pente DOUBLE PRECISION,
    hauteur DOUBLE PRECISION,
    orientation DOUBLE PRECISION,
    id_milieu INT,
    CONSTRAINT PK_localisation PRIMARY KEY (id_localisation),
    CONSTRAINT FK_localisation_milieu
        FOREIGN KEY (id_milieu)
        REFERENCES milieu_specifique (id_milieu)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE biodiversite_localisee (
    id_loc INT,
    id_bio INT,
    CONSTRAINT PK_biodiversite_localisee PRIMARY KEY (id_loc, id_bio),
    CONSTRAINT FK_biodiversite_localisee_localisation
        FOREIGN KEY (id_loc)
        REFERENCES localisation (id_localisation)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_biodiversite_localisee_biodiversite
        FOREIGN KEY (id_bio)
        REFERENCES biodiversite (id_biodiversite)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE categorie_variable (
    id_categorie INT GENERATED BY DEFAULT AS IDENTITY,
    nom VARCHAR(255),
    id_parent INT,
    CONSTRAINT PK_categorie_variable PRIMARY KEY (id_categorie),
    CONSTRAINT FK_categorie_variable_parent
        FOREIGN KEY (id_parent)
        REFERENCES categorie_variable (id_categorie)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT CK_categorie_differente 
        CHECK (id_categorie <> id_parent)
);

CREATE TABLE variable_mesuree (
    id_variable_mesuree INT GENERATED BY DEFAULT AS IDENTITY,
    type_mesure VARCHAR(255),
    unite_mesure VARCHAR(255),
    description_var_mesuree TEXT,
    CONSTRAINT PK_variable_mesuree PRIMARY KEY (id_variable_mesuree)
);

CREATE TABLE possede_categorie (
    id_variable INT,
    id_categorie INT,
    CONSTRAINT PK_possede_categorie PRIMARY KEY (id_variable, id_categorie),
    CONSTRAINT FK_possede_categorie_variable
        FOREIGN KEY (id_variable)
        REFERENCES variable_mesuree (id_variable_mesuree)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_possede_categorie_categorie
        FOREIGN KEY (id_categorie)
        REFERENCES categorie_variable (id_categorie)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE structure_fichier (
    id_structure INT GENERATED BY DEFAULT AS IDENTITY,
    extension VARCHAR(50),
    nom_colonnes TEXT,
    nb_colonnes INT,
    colonnes_a_traiter TEXT,
    format_titre VARCHAR(255),
    groupes_regex TEXT,
    nom_instrument VARCHAR(255) NOT NULL,
    CONSTRAINT uq_nom_instrument UNIQUE (nom_instrument),
    CONSTRAINT PK_structure_fichier PRIMARY KEY (id_structure),
    CONSTRAINT CK_structure_fichier_nb_colonnes CHECK (nb_colonnes >= 1)
);

CREATE TABLE instrument_mesure (
    id_instrument INT GENERATED BY DEFAULT AS IDENTITY,
    num_instrument VARCHAR(255) NOT NULL,
    modele VARCHAR(255),
    num_serie VARCHAR(255),
    nom_outil VARCHAR(255),
    pas_temps REAL,
    fuseau_horaire INT,
    description_instrument TEXT,
    id_structure INT NOT NULL,
    CONSTRAINT PK_instrument_mesure PRIMARY KEY (id_instrument),
    CONSTRAINT FK_instrument_mesure_structure
        FOREIGN KEY (id_structure)
        REFERENCES structure_fichier (id_structure)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT uq_num_instrument
        UNIQUE (num_instrument) 
);

CREATE TABLE collecte_instrument (
    id_collecteur INT,
    id_instrument INT,
    CONSTRAINT PK_collecte_instrument PRIMARY KEY (id_collecteur, id_instrument),
    CONSTRAINT FK_collecte_instrument_collecteur
        FOREIGN KEY (id_collecteur)
        REFERENCES collecteur (id_collecteur)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_collecte_instrument_instrument
        FOREIGN KEY (id_instrument)
        REFERENCES instrument_mesure (id_instrument)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE remplacement_instrument (
    id_instrument INT,
    id_nouvel_instrument INT,
    date_remplacement DATE,
    raison_remplacement TEXT,
    CONSTRAINT PK_remplacement_instrument
        PRIMARY KEY (id_instrument, id_nouvel_instrument),
    CONSTRAINT FK_remplacement_instrument_ancien
        FOREIGN KEY (id_instrument)
        REFERENCES instrument_mesure (id_instrument)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT FK_remplacement_instrument_nouveau
        FOREIGN KEY (id_nouvel_instrument)
        REFERENCES instrument_mesure (id_instrument)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT CK_remplacement_instrument_diff
        CHECK (id_instrument <> id_nouvel_instrument)
);

CREATE TABLE est_referent_de (
    id_referent INT,
    id_instrument INT,
    date_debut DATE,
    date_fin DATE,
    CONSTRAINT PK_est_referent_de PRIMARY KEY (id_referent, id_instrument, date_debut),
    CONSTRAINT FK_est_referent_de_referent_instrument
        FOREIGN KEY (id_referent)
        REFERENCES referent_instrument (id_referent)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_est_referent_de_instrument
        FOREIGN KEY (id_instrument)
        REFERENCES instrument_mesure (id_instrument)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT CK_est_referent_de_dates CHECK (date_debut <= date_fin)
);

CREATE TABLE instrument_projet (
    id_projet INT,
    id_instrument INT,
    CONSTRAINT PK_instrument_projet PRIMARY KEY (id_projet, id_instrument),
    CONSTRAINT FK_instrument_projet_projet
        FOREIGN KEY (id_projet)
        REFERENCES projet (id_projet)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_instrument_projet_instrument
        FOREIGN KEY (id_instrument)
        REFERENCES instrument_mesure (id_instrument)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE capteur (
    id_capteur INT,
    date_activation DATE,
    id_instrument INT NOT NULL,
    CONSTRAINT PK_capteur PRIMARY KEY (id_capteur),
    CONSTRAINT FK_capteur_capteur_generique
        FOREIGN KEY (id_capteur)
        REFERENCES capteur_generique (id_capteur_generique)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_capteur_instrument
        FOREIGN KEY (id_instrument)
        REFERENCES instrument_mesure (id_instrument)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE TABLE maintenance_capteur (
    id_probleme INT GENERATED BY DEFAULT AS IDENTITY,
    date_debut TIMESTAMP,
    date_fin TIMESTAMP,
    description TEXT,
    id_capteur INT NOT NULL,
    CONSTRAINT PK_maintenance_capteur PRIMARY KEY (id_probleme),
    CONSTRAINT FK_maintenance_capteur_capteur
        FOREIGN KEY (id_capteur)
        REFERENCES capteur (id_capteur)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT CK_maintenance_capteur_dates CHECK (date_debut <= date_fin)
);

CREATE TABLE remplacement_capteur (
    id_capteur INT,
    id_nouveau_capteur INT,
    date_remplacement DATE,
    raison_remplacement TEXT,
    CONSTRAINT PK_remplacement_capteur
        PRIMARY KEY (id_capteur, id_nouveau_capteur),
    CONSTRAINT FK_remplacement_capteur_ancien
        FOREIGN KEY (id_capteur)
        REFERENCES capteur (id_capteur)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT FK_remplacement_capteur_nouveau
        FOREIGN KEY (id_nouveau_capteur)
        REFERENCES capteur (id_capteur)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT CK_remplacement_capteur_diff
        CHECK (id_capteur <> id_nouveau_capteur)
);

CREATE TABLE capteur_localise (
    id_capteur_gen INT,
    id_loc INT,
    date_debut DATE,
    date_fin DATE,
    CONSTRAINT PK_capteur_localise PRIMARY KEY (id_capteur_gen, id_loc, date_debut),
    CONSTRAINT FK_capteur_localise_capteur_generique
        FOREIGN KEY (id_capteur_gen)
        REFERENCES capteur_generique (id_capteur_generique)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_capteur_localise_localisation
        FOREIGN KEY (id_loc)
        REFERENCES localisation (id_localisation)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT CK_capteur_localise_dates CHECK (date_debut <= date_fin)
);

CREATE TABLE serie_temporelle (
    id_st INT GENERATED BY DEFAULT AS IDENTITY,
    date_debut TIMESTAMP,
    date_fin TIMESTAMP,
    max_mesure DOUBLE PRECISION,
    min_mesure DOUBLE PRECISION,
    moyenne_mesure DOUBLE PRECISION,
    nb_mesures INT,
    id_capteur_gen INT NOT NULL,
    id_loc INT NOT NULL,
    date_capteur_loc DATE NOT NULL,
    id_variable_mesuree INT NOT NULL,
    CONSTRAINT PK_serie_temporelle PRIMARY KEY (id_st),
    CONSTRAINT FK_serie_temporelle_capteur_localise
        FOREIGN KEY (id_capteur_gen, id_loc, date_capteur_loc)
        REFERENCES capteur_localise (id_capteur_gen, id_loc, date_debut)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_serie_temporelle_variable_mesuree 
        FOREIGN KEY (id_variable_mesuree) 
        REFERENCES variable_mesuree (id_variable_mesuree) 
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT uq_serie_temporelle_capteur_loc
        UNIQUE (id_capteur_gen, id_loc, date_capteur_loc)

);

CREATE TABLE source_donnees (
    id_source INT GENERATED BY DEFAULT AS IDENTITY,
    extension VARCHAR(50),
    nom_source VARCHAR(255),
    chemin_source VARCHAR(500),
    date_import TIMESTAMP,
    date_recueil TIMESTAMP,
    commentaire TEXT,
    type_source VARCHAR(50),
    id_responsable INT NOT NULL,
    id_st INT NOT NULL,
    id_struct INT,
    CONSTRAINT PK_source_donnees PRIMARY KEY (id_source),
    CONSTRAINT FK_source_donnees_responsable
        FOREIGN KEY (id_responsable)
        REFERENCES responsable_fichier (id_responsable)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_source_donnees_serie_temporelle
        FOREIGN KEY (id_st)
        REFERENCES serie_temporelle (id_st)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_source_donnees_structure_fichier
        FOREIGN KEY (id_struct)
        REFERENCES structure_fichier (id_structure)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT CK_source_donnees_type
        CHECK (type_source IN ('fichier_mesure', 'dossier_audio', 'dossier_image'))
);

CREATE TABLE mesure (
    id_mesure INT GENERATED BY DEFAULT AS IDENTITY,
    valeur_mesure DOUBLE PRECISION,
    date_heure TIMESTAMP,
    description_mesure TEXT,
    statut VARCHAR(255),
    id_mesure_associee INT,
    id_st INT NOT NULL,
    CONSTRAINT PK_mesure PRIMARY KEY (id_mesure),
    CONSTRAINT FK_mesure_mesure_associee
        FOREIGN KEY (id_mesure_associee)
        REFERENCES mesure (id_mesure)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT FK_mesure_serie_temporelle
        FOREIGN KEY (id_st)
        REFERENCES serie_temporelle (id_st)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT CK_mesure_differente
        CHECK (id_mesure <> id_mesure_associee),
    CONSTRAINT CK_mesure_statut
        CHECK (statut IN ('principale', 'secondaire'))
);

CREATE TABLE coefficient_correcteur (
    id_coeff_correcteur INT GENERATED BY DEFAULT AS IDENTITY,
    valeur DOUBLE PRECISION,
    date_calibration TIMESTAMP,
    id_capteur INT NOT NULL,
    unite VARCHAR(255),
    CONSTRAINT PK_coefficient_correcteur PRIMARY KEY (id_coeff_correcteur),
    CONSTRAINT uq_coefficient_correcteur_date_capteur
        UNIQUE (date_calibration, id_capteur),
    CONSTRAINT FK_coefficient_correcteur_capteur
        FOREIGN KEY (id_capteur)
        REFERENCES capteur (id_capteur)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE correction_mesure (
    id_coeff INT,
    id_mesure INT,
    CONSTRAINT PK_correction_mesure PRIMARY KEY (id_coeff, id_mesure),
    CONSTRAINT FK_correction_mesure_coeff
        FOREIGN KEY (id_coeff)
        REFERENCES coefficient_correcteur (id_coeff_correcteur)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_correction_mesure_mesure
        FOREIGN KEY (id_mesure)
        REFERENCES mesure (id_mesure)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE membre_groupe (
    id_groupe_recolte INT,
    id_recolteur INT,
    id_capteur_generique INT,
    CONSTRAINT PK_membre_groupe
        PRIMARY KEY (id_groupe_recolte, id_recolteur, id_capteur_generique),
    CONSTRAINT FK_membre_groupe_groupe
        FOREIGN KEY (id_groupe_recolte)
        REFERENCES groupe_recolte (id_groupe)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_membre_groupe_recolteur
        FOREIGN KEY (id_recolteur, id_capteur_generique)
        REFERENCES recolteur (id_recolteur, id_capteur_generique)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE membre_projet (
    id_recolteur INT,
    id_capteur_generique INT,
    id_projet INT,
    CONSTRAINT PK_membre_projet
        PRIMARY KEY (id_recolteur, id_capteur_generique, id_projet),
    CONSTRAINT FK_membre_projet_recolteur
        FOREIGN KEY (id_recolteur, id_capteur_generique)
        REFERENCES recolteur (id_recolteur, id_capteur_generique)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_membre_projet_projet
        FOREIGN KEY (id_projet)
        REFERENCES projet (id_projet)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);





-- =========================================================
-- TRIGGERS FONCTION (en pgplsql)
-- =========================================================

CREATE OR REPLACE FUNCTION verification_heritage_disjoint_capteur_generique()
RETURNS trigger AS $$
DECLARE
    v_id INT;
BEGIN
    -- Récupère l'id inséré peu importe la table source
    IF TG_TABLE_NAME = 'recolteur' THEN
        v_id := NEW.id_capteur_generique;
        IF EXISTS (SELECT 1 FROM capteur WHERE id_capteur = v_id) THEN
            RAISE EXCEPTION 'L''id capteur générique % est déjà enregistré comme capteur.', v_id;
        END IF;
    ELSIF TG_TABLE_NAME = 'capteur' THEN
        v_id := NEW.id_capteur;
        IF EXISTS (SELECT 1 FROM recolteur WHERE id_capteur_generique = v_id) THEN
            RAISE EXCEPTION 'L''id capteur générique % est déjà enregistré comme récolteur.', v_id;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- La variable spéciale TG_TABLE_NAME fournie par PostgreSQL 
-- contient le nom de la table qui a déclenché le trigger,
-- ce qui permet à une seule fonction de se comporter différemment selon le contexte d'appel.
-- D'après Claude
--==========================================================

CREATE OR REPLACE FUNCTION maj_attributs_st()
RETURNS trigger AS $$
BEGIN
    -- Mise à jour des attribus nb_mesures, max_mesure, min_mesure et moyenne_mesure de la série temporelle
    UPDATE serie_temporelle
    SET 
        nb_mesures = nb_mesures + 1,
        max_mesure = GREATEST(
            COALESCE(max_mesure, NEW.valeur_mesure::DOUBLE PRECISION),
            NEW.valeur_mesure::DOUBLE PRECISION
        ),
        min_mesure = LEAST(
            COALESCE(min_mesure, NEW.valeur_mesure::DOUBLE PRECISION),
            NEW.valeur_mesure::DOUBLE PRECISION
        ),
        moyenne_mesure = (
            (COALESCE(moyenne_mesure, 0) * COALESCE(nb_mesures, 0) + NEW.valeur_mesure::DOUBLE PRECISION)
            / (COALESCE(nb_mesures, 0) + 1)
        )
    WHERE id_st = NEW.id_st; --id_st est l'id de la ST de la table serie_temporelle et NEW.id_st est
    -- l'id de la serie temporelle de la table mesure

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================================================
-- TRIGGERS APPELS (en pgplsql)
-- =========================================================
CREATE TRIGGER trigger_verification_heritage_disjoint_recolteur
BEFORE INSERT ON recolteur
FOR EACH ROW
EXECUTE FUNCTION verification_heritage_disjoint_capteur_generique();

CREATE TRIGGER trigger_verification_heritage_disjoint_capteur
BEFORE INSERT ON capteur
FOR EACH ROW
EXECUTE FUNCTION verification_heritage_disjoint_capteur_generique();
--============================================================

CREATE TRIGGER trigger_maj_attributs_st
AFTER INSERT ON mesure
FOR EACH ROW
EXECUTE FUNCTION maj_attributs_st();

--======================================================
--Remplissage de la table categorie_variable
--======================================================

INSERT INTO categorie_variable (nom) VALUES
    ('Données Biologiques'),
    ('Données Environnementales');

INSERT INTO categorie_variable (nom, id_parent) VALUES
    ('Faune', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Données Biologiques')),
    ('Végétation', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Données Biologiques'));

INSERT INTO categorie_variable (nom, id_parent) VALUES
    ('Climat', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Données Environnementales')),
    ('Sol', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Données Environnementales')),
    ('Perturbation Anthropique', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Données Environnementales'));

INSERT INTO categorie_variable (nom, id_parent) VALUES
    ('Sol Faune', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Faune')),
    ('Ornithologie', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Faune')),
    ('Entomologie', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Faune')),
    ('Chiroptérologie', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Faune'));

INSERT INTO categorie_variable (nom, id_parent)
VALUES
    ('Liste espèces', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Végétation')),
    ('Longueur Racine', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Végétation')),
    ('Traits Foliaires', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Végétation')),
    ('Croissance Aérienne', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Végétation'));


INSERT INTO categorie_variable (nom, id_parent) VALUES
    ($$Qualité Air$$, (SELECT id_categorie FROM categorie_variable WHERE nom = 'Climat')),
    ('Données Météorologiques', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Climat'));

INSERT INTO categorie_variable (nom, id_parent) VALUES
    ('CO2', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Qualité Air')),
    ('O3', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Qualité Air')),
    ('NO2', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Qualité Air')),
    ('SO2', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Qualité Air')),
    ('COV', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Qualité Air')),
    ('Microparticules', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Qualité Air'));

INSERT INTO categorie_variable (nom, id_parent) VALUES
    ('Température Air', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Données Météorologiques')),
    ('Humidité Air', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Données Météorologiques')),
    ('Vent', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Données Météorologiques')),
    ('Précipitations', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Données Météorologiques')),
    ('Ensoleillement', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Données Météorologiques'));

INSERT INTO categorie_variable (nom, id_parent) VALUES
    ('Infiltration', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Sol')),
    ('Température Sol', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Sol')),
    ('Humidité Sol', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Sol')),
    ('PH', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Sol'));

INSERT INTO categorie_variable (nom, id_parent) VALUES 
    ('Pollution Sonore', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Perturbation Anthropique')),
    ('Pollution Lumineuse', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Perturbation Anthropique')),
    ('Gestion Espaces Verts', (SELECT id_categorie FROM categorie_variable WHERE nom = 'Perturbation Anthropique'));


INSERT INTO structure_fichier (extension, nom_colonnes, nb_colonnes, colonnes_a_traiter, format_titre, nom_instrument) VALUES ('xlsx', '#; Date et heure (CET/CEST) || CET || CEST; Température, °C', 3, '0; 0; 1', '\(n°[0-9]+\) [0-9]+ ? [0-9]+-[0-9]+-[0-9]+ [0-9]+_[0-9]+_[0-9]+ CES?T\.xlsx', 'Hobo');  